name: resutoran_app
description: Resutoran App. Flutter application restaurant catalogue

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  responsive_framework: ^0.1.0
  firebase_core: ^1.1.0
  cloud_firestore: ^2.1.0
  firebase_auth: ^1.2.0
  provider: ^5.0.0
  get_it: ^7.1.3
  get: ^4.1.4
  geocoder: ^0.2.1
  flutter_login: ^1.1.0
  font_awesome_flutter: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/
